name: pro_time
description: Projects time tracking app.

version: 1.1.0+2

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  hive: ^1.0.0
  hive_flutter: ^0.2.1
  path_provider: ^1.3.0
  provider: ^3.1.0
  intl: ^0.16.0
  flutter_colorpicker: ^0.2.6
  auto_animated: ^1.2.2
  flutter_slidable: ^0.5.3
  auto_size_text: ^2.1.0
  flutter_picker: ^1.0.15

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^0.5.2
  build_runner: ^1.7.1
  flutter_launcher_icons: "^0.7.3"

flutter:
  uses-material-design: true
  assets:
    - assets/play.png
    - assets/pause.png
    - assets/stop.png

flutter_icons:
  android: "launcher_icon" 
  ios: true
  image_path: "assets/icon.png"